### ISSUE TITLE
Change the default code of C++

### ISSUE THREAD

**Issue by dhwaj1902** [coding-minutes/coding-minutes-ide#8]
Currently, the c++ default code/stub is ``\n#include <iostream>\nusing namespace std;\n\nint main() {\n\t// your code goes here\n\treturn 0;\n}\n\n``, the problem is when we run this program there is no output because there is no cout and we have not handle such condition.

We can resolve this by adding ``cout`` like this ``\n#include <iostream>\nusing namespace std;\n\nint main() {\n\t// your code goes here\n\tcout<<"Hello World";\n\treturn 0;\n}\n\n``. This will run the program without any error.

**Comment by soumya997** [comment]
It would also be great if you guys could add `#include<bits/stdc++.h>` in the default template instead of `#include<iostream>`. I believe most of the time everybody needs to change `#include<iostream>` to `#include<bits/stdc++.h>`. And changing this every time you open a new tab for the IDE is a bit tedious (when you are in a hurry).

**Comment by Amoghtech** [comment]
Hey can I work on this issue?

**Comment by tarunluthra123** [comment]
This issue stems from the [Judge Proxy](https://github.com/coding-minutes/judge-proxy) repo as the IDE simply displays the exact snippets it fetches from Judge Proxy (via [ide-proxy](https://github.com/coding-minutes/ide-proxy)).

I'll be marking this issue closed for now on this repository and creating new one on Judge Proxy repo for this reason as it is more relevant there. 

If any of you would like to contribute to it, feel free to pick it up over there. 

@dhwaj1902 @soumya997 @Amoghtech
